forge "https://forgeapi.puppetlabs.com"
mod 'hunner/hiera', '1.3.1'
mod 'zack/r10k', '3.1.1'
mod 'puppet-nginx', '0.6.0'
mod 'puppet-nodejs', '2.3.0'
mod 'puppetlabs/concat', '1.2.5'
mod 'puppetlabs/firewall', '1.8.0'
mod 'puppetlabs/inifile', '1.4.3'
mod 'puppetlabs/stdlib', '4.11.0'
mod 'puppetlabs-apt', '2.2.2'
mod 'puppetlabs/ruby'
mod 'puppetlabs/gcc'
mod 'puppetlabs/pe_gem'
mod 'croddy/make'
mod 'gentoo/portage'
mod 'puppetlabs/git', '0.4.0'
mod 'puppetlabs/vcsrepo', '1.3.2'
